---
- name: setup AWS resources
  cloudformation:
    stack_name: "Elasticsearch"
    state: "present"
    region: "{{ aws_region }}"
    template: "{{ role_path }}/files/elasticsearch_cluster.yaml"
    template_parameters: 
      KeyName: "{{ my_key }}"
      InstanceType: "{{ instance_type }}"
      ImageId: "{{ image_id }}"
      SSHLocation: "{{ source_ip }}"
