---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation templete to spin up an instance for elasticsearch'
Parameters:
  KeyName:
    Description: Existing KeyPair
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be existing KeyPair
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
  SSHLocation:
    Description: Lock down SSH access
    Type: String
    Default: 0.0.0.0/0
  ImageId:
    Description: AMI to spin up from
    Type: String
    Default: ami-0ff8a91507f77f867
Resources:
  ElasticsearchCluster:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Fn::GetAZs: ''
      LaunchConfigurationName: 
        Ref: ClusterConfig
      DesiredCapacity: 1
      MaxSize: 1
      MinSize: 1
  ClusterConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0cd27db22c04f7033
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      InstanceType: 
        Ref: InstanceType
      KeyName:
        Ref: KeyName
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH Access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp:
          Ref: SSHLocation
